//
//  Identifier.swift
//  SwiftTagger
//
//  Created by Nolaine Crusher on 9/28/20.
//

//import Foundation
//enum Identifier: String, CaseIterable {
//    case acknowledgment
//    case album
//    case albumArtist
//    case albumArtistSort
//    case albumSort
//    case appleStoreCountryID
//    case arranger
//    case arrangerKeywords
//    case artDirector
//    case artist
//    case artistID
//    case artistKeywords
//    case artistSort
//    case artistWebpage
//    case audioFileWebpage
//    case audioSourceWebpage
//    case bpm
//    case compilation
//    case composer
//    case composerID
//    case composerKeywords
//    case composerSort
//    case conductor
//    case conductorID
//    case contentRating
//    case copyright
//    case copyrightWebpage
//    case coverArt
//    case description
//    case director
//    case discNumber
//    case encodingDateTime
//    case encodedBy
//    case encoderAndSettings
//    case executiveProducer
//    case gaplessPlayback
//    case genreCustom
//    case genrePredefined
//    case genreID
//    case grouping
//    case information
//    case initialKey
//    case involvedPeopleList
//    case isrc
//    case iTunesAccount
//    case iTunesAccountType
//    case label
//    case labelWebpage
//    case languages
//    case length
//    case linerNotes
//    case longDescription
//    case lyrics
//    case lyricist
//    case mediaKind
//    case mood
//    case movementCount
//    case movement
//    case movementNumber
//    case musicianCreditsList
//    case narrator
//    case originalAlbum
//    case originalArtist
//    case originalFilename
//    case originalLyricist
//    case originalReleaseDateTime
//    case owner
//    case paymentWebpage
//    case performers
//    case playlistDelay
//    case playlistID
//    case podcast
//    case podcastCategory
//    case podcastDescription
//    case podcastID
//    case podcastKeywords
//    case podcastFeed
//    case producer
//    case producerKeywords
//    case producedNotice
//    case publisher
//    case publisherWebpage
//    case purchaseDateTime
//    case radioStation
//    case radioStationOwner
//    case radioStationWebpage
//    case rating
//    case recordCompany
//    case recordCompanyWebpage
//    case recordingDateTime
//    case releaseDateTime
//    case requirements
//    case sellerID
//    case setOrTrackSubtitle
//    case showWorkAndMovement
//    case soundEngineer
//    case softwareVersion
//    case soloist
//    case songDescription
//    case songwriter
//    case songwriterKeywords
//    case sourceCredit
//    case subtitle
//    case subtitleKeywords
//    case taggingDateTime
//    case title
//    case titleKeywords
//    case titleSort
//    case thanks
//    case trackNumber
//    case seriesEpisodeNumber
//    case seriesEpisodeTitle
//    case seriesDistributor
//    case seriesSeason
//    case series
//    case seriesDescription
//    case seriesSort
//    case userDefined
//    case work
//    case writer
//    case year
//}
